on:
  push:

name: Lint & rename

jobs:
  lint_csv:
    name: Lint CSV

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: "./"
          sparse-checkout-cone-mode: true

      - name: Lint CSV
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.csv"
          find_path: "."

  rename_snippets:
    name: Rename snippets

    runs-on: ubuntu-latest

    needs: [lint_csv]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Remove existing renamed files
        run: |
          rm -rf renamed/

      - name: Rename files using transcriptions
        run: |
          python3 ./rename_snippets.py

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add renamed/
          git commit -m "chore: rename snippets"
          git push
